from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1323, 833)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 50, 1321, 591))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_save_close = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_save_close.setGeometry(QtCore.QRect(1160, 710, 151, 41))
        self.pushButton_save_close.setObjectName("pushButton_save_close")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 640, 311, 142))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit_samplerate = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_samplerate.setObjectName("lineEdit_samplerate")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_samplerate)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_channal = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_channal.setObjectName("lineEdit_channal")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_channal)
        self.LineEdit_downsample = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LineEdit_downsample.setObjectName("LineEdit_downsample")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_downsample)
        self.Label = QtWidgets.QLabel(self.formLayoutWidget)
        self.Label.setObjectName("Label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label)
        self.lineEdit_interval = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_interval.setObjectName("lineEdit_interval")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_interval)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.pushButton_set = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_set.setObjectName("pushButton_set")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pushButton_set)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(480, 640, 301, 114))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.LineEdit_savetime = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LineEdit_savetime.setObjectName("LineEdit_savetime")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit_savetime)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_wave_filename = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_wave_filename.setObjectName("lineEdit_wave_filename")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_wave_filename)
        self.Label_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.Label_2.setObjectName("Label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_2)
        self.pushButton_auto_save_close = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.pushButton_auto_save_close.setObjectName("pushButton_auto_save_close")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pushButton_auto_save_close)
        self.lineEdit_file_times = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_file_times.setObjectName("lineEdit_file_times")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_file_times)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.pushButton_play = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_play.setGeometry(QtCore.QRect(1160, 640, 151, 41))
        self.pushButton_play.setObjectName("pushButton_play")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 631, 51))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_bar = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_bar.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_bar.setObjectName("verticalLayout_bar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1323, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        # 配置文件
        with open("configuration_file.txt", 'r', encoding="utf-8") as fc:
            fc_list = fc.readlines()
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "示波器测试版"))
        self.pushButton_save_close.setText(_translate("MainWindow", "录制"))
        self.label.setText(_translate("MainWindow", "采样率："))
        self.lineEdit_samplerate.setText(_translate("MainWindow", fc_list[7][:-1]))   # 采用率设置
        self.label_2.setText(_translate("MainWindow", "输出通道："))
        self.LineEdit_downsample.setText(_translate("MainWindow", "10"))
        self.Label.setText(_translate("MainWindow", "波形显示下采样："))
        self.lineEdit_interval.setText(_translate("MainWindow", "30"))
        self.label_4.setText(_translate("MainWindow", "波形图刷新速度："))
        self.pushButton_set.setText(_translate("MainWindow", "设置"))
        self.LineEdit_savetime.setText(_translate("MainWindow", fc_list[3][:-1]))  # 单个文件保存时间
        self.label_3.setText(_translate("MainWindow", "自动保存文件夹："))
        self.lineEdit_wave_filename.setText(_translate("MainWindow", fc_list[1][:-1]))  # 文件夹名称
        self.Label_2.setText(_translate("MainWindow", "自动保存时间："))
        self.pushButton_auto_save_close.setText(_translate("MainWindow", "自动录制"))
        self.lineEdit_file_times.setText(_translate("MainWindow", fc_list[5][:-1]))    # 文件保存个数
        self.label_5.setText(_translate("MainWindow", "自动保存文件个数："))
        self.pushButton_play.setText(_translate("MainWindow", "显示波形"))